#!/bin/bash

source init_wor
cleos push action wsc.code transferitem '{"to":"turnip2", "tx_item":{"ItemName":"Sword", "ItemClass":"Weapon","Nuance":"0000", "Owner":"turnip", "OriginWorld":"turnip", "GenesisTime":"429762", "Stake":"1.00 WOR"}}' -p turnip@active
